/**
 * /[locale]/lenders/[slug] — Lender Profile Page (ISR Shell)
 *
 * Story 2.5: ISR Shell & Metadata.
 *
 * ISR strategy:
 * - generateStaticParams: pre-generates all ~4,092 slugs × {zh, en} at build time.
 * - unstable_cache wraps the DB lookup; tag = lender:{slug}, revalidate = 7 days.
 * - revalidateTag('lender:{slug}') in admin action handlers purges individual pages.
 * - stale-while-revalidate is Next.js default — stale content served during refresh.
 *
 * Metadata:
 * - generateMetadata: title, canonical (TC = /zh/), og:*, twitter:card, JSON-LD.
 *
 * Page body (Story 2.5): ISR shell only — <h1> with companyNameZh.
 * Full content sections (profile card, reviews, activity feed) are added in Story 2.6.
 *
 * Next.js 16: params is a Promise and must be awaited.
 * ARCH-9: TC (/zh/) is canonical — all canonical links point to the zh URL.
 */

import { notFound } from 'next/navigation'
import { unstable_cache } from 'next/cache'
import type { Metadata } from 'next'
import { db } from '@/lib/db'
import { isLocale } from '@/locales'
import { getLocalizedField } from '@/lib/utils/get-localized-field'
import { LicenceBadge } from '@/components/directory/LicenceBadge'
import { LicencePanel } from '@/components/profile/LicencePanel'
import { LoanTypeTags } from '@/components/profile/LoanTypeTags'
import { LenderPulse } from '@/components/profile/LenderPulse'
import { EligibilityChips } from '@/components/profile/EligibilityChips'

// ─── Site config ──────────────────────────────────────────────────────────────

const SITE_URL = 'https://hklend.hk'
const REVALIDATE_SECONDS = 604800 // 7 days

// ─── Types ────────────────────────────────────────────────────────────────────

type PageParams = Promise<{ locale: string; slug: string }>

type LenderData = {
  slug: string
  licenceNumber: string
  licenceStatus: string
  companyNameZh: string
  companyNameEn: string | null
  addressZh: string
  addressEn: string | null
  districtZh: string
  districtEn: string | null
  phone: string | null
  websiteUrl: string | null
  loanTypeTags: string[]
  eligibilityTags: string[]
  adminNote: string | null
  activityEvents: Array<{
    descriptionZh: string
    descriptionEn: string | null
  }>
}

// ─── Cached DB lookup ─────────────────────────────────────────────────────────

/**
 * getLenderBySlug — wraps the DB query in unstable_cache.
 *
 * Tag `lender:{slug}` is purged by:
 *   - The ISR revalidation webhook (ARCH-11) called by the HKMA scraper.
 *   - Admin server actions after approving a lender change.
 *
 * `revalidate: 604800` = 7-day TTL as a fallback even without a tag purge.
 * Stale-while-revalidate: Next.js serves stale content while re-fetching.
 */
function getLenderBySlug(slug: string): Promise<LenderData | null> {
  return unstable_cache(
    async () =>
      db.lender.findUnique({
        where: { slug },
        select: {
          slug: true,
          licenceNumber: true,
          licenceStatus: true,
          companyNameZh: true,
          companyNameEn: true,
          addressZh: true,
          addressEn: true,
          districtZh: true,
          districtEn: true,
          phone: true,
          websiteUrl: true,
          loanTypeTags: true,
          eligibilityTags: true,
          adminNote: true,
          activityEvents: {
            orderBy: { detectedAt: 'desc' },
            take: 1,
            select: {
              descriptionZh: true,
              descriptionEn: true,
            },
          },
        },
      }),
    [`lender-${slug}`],
    {
      tags: [`lender:${slug}`],
      revalidate: REVALIDATE_SECONDS,
    }
  )()
}

// ─── generateStaticParams ─────────────────────────────────────────────────────

/**
 * Pre-generate all lender × locale combos at build time.
 *
 * Fetches every slug from the DB and emits one param set per locale.
 * Both TC and EN pages are generated as static HTML.
 */
export async function generateStaticParams() {
  const lenders = await db.lender.findMany({ select: { slug: true } })

  return lenders.flatMap(({ slug }) => [
    { locale: 'zh', slug },
    { locale: 'en', slug },
  ])
}

// ─── Metadata ─────────────────────────────────────────────────────────────────

/**
 * Dynamic per-lender metadata.
 *
 * Title:
 *   TC: "{companyNameZh} — hklend"
 *   EN: "{companyNameEn ?? companyNameZh} — hklend"
 *
 * Canonical: always points to the TC (/zh/) URL (ARCH-9).
 * og:image: /og/lender/{slug}.png — generated by the OG image route (Story 2.x).
 */
export async function generateMetadata({
  params,
}: {
  params: PageParams
}): Promise<Metadata> {
  const { locale, slug } = await params
  const lender = await getLenderBySlug(slug)

  if (!lender) return { title: 'Not Found — hklend' }

  const isZh = locale === 'zh'
  const displayName = isZh
    ? lender.companyNameZh
    : (lender.companyNameEn ?? lender.companyNameZh)

  const title = `${displayName} — hklend`
  const description = isZh
    ? `查看 ${lender.companyNameZh} 的牌照狀態、地址及聯絡資料。持牌放債人資料由香港公司登記冊提供。`
    : `View licence status, address, and contact details for ${displayName}. Licensed money lender data from the Hong Kong Money Lenders Register.`

  // ARCH-9: TC URL is canonical — all en pages declare the zh URL as canonical.
  const canonicalUrl = `${SITE_URL}/zh/lenders/${slug}`
  const pageUrl = `${SITE_URL}/${locale}/lenders/${slug}`
  const ogImageUrl = `${SITE_URL}/og/lender/${slug}.png`

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title,
      description,
      url: pageUrl,
      images: [{ url: ogImageUrl }],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl],
    },
  }
}

// ─── JSON-LD builder ──────────────────────────────────────────────────────────

function buildJsonLd(lender: LenderData, isZh: boolean) {
  const name = isZh
    ? lender.companyNameZh
    : (lender.companyNameEn ?? lender.companyNameZh)
  const streetAddress = isZh
    ? lender.addressZh
    : (lender.addressEn ?? lender.addressZh)
  const addressLocality = isZh
    ? lender.districtZh
    : (lender.districtEn ?? lender.districtZh)

  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name,
    identifier: lender.licenceNumber,
    address: {
      '@type': 'PostalAddress',
      streetAddress,
      addressLocality,
      addressCountry: 'HK',
    },
    ...(lender.phone ? { telephone: lender.phone } : {}),
    ...(lender.websiteUrl ? { url: lender.websiteUrl } : {}),
  }
}

// ─── Page ─────────────────────────────────────────────────────────────────────

/**
 * ISR shell — Story 2.5.
 *
 * The page body is intentionally minimal for this story.
 * Profile card, reviews, and activity feed sections are added in Story 2.6.
 */
export default async function LenderProfilePage({
  params,
}: {
  params: PageParams
}) {
  const { locale, slug } = await params

  if (!isLocale(locale)) notFound()

  const lender = await getLenderBySlug(slug)

  if (!lender) notFound()

  const isZh = locale === 'zh'
  const jsonLd = buildJsonLd(lender, isZh)

  return (
    <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6 space-y-6">
      {/* JSON-LD structured data — hoisted to <head> by Next.js */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Header: name + licence status badge */}
      <div className="flex flex-wrap items-start gap-3">
        <h1 className="text-2xl font-semibold text-[#264a58]">
          {getLocalizedField(lender, 'companyName', locale)}
        </h1>
        <LicenceBadge licenceStatus={lender.licenceStatus} locale={locale} size="lg" />
      </div>

      {/* Licence details panel */}
      <LicencePanel lender={lender} locale={locale} />

      {/* Eligibility chips */}
      <EligibilityChips tags={lender.eligibilityTags} locale={locale} />

      {/* Loan type tags — each links to filtered directory */}
      <LoanTypeTags tags={lender.loanTypeTags} locale={locale} />

      {/* Lender Pulse — most recent activity event; absent when none */}
      <LenderPulse events={lender.activityEvents} locale={locale} />

      {/* Admin note callout box (brand-card background) */}
      {lender.adminNote && (
        <div className="rounded-xl bg-brand-card p-4">
          <p className="text-sm text-[#264a58]">{lender.adminNote}</p>
        </div>
      )}
    </main>
  )
}
